trigger:
- main

variables:
  registry: 'maizmazin/vproappdock'
  imageName: 'vprofile'

stages:
- stage: Build
  jobs:
  - job: BuildProject
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        mvn clean install -DskipTests  # Build the Maven project
      displayName: 'Build Project'

  - job: CheckDocker
    dependsOn: BuildProject  # This job depends on the previous job
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        docker --version  # Check Docker version
      displayName: 'Check Docker Version'

  - job: StartDocker
    dependsOn: CheckDocker  # This job depends on the previous job
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        sudo service docker start  # Start Docker daemon
      displayName: 'Start Docker Daemon'

  - job: BuildDockerImage
    dependsOn: StartDocker  # This job depends on the previous job
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        docker build -t $(registry):$(Build.BuildId) .  # Build Docker image using build number
      displayName: 'Build Docker Image'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(System.DefaultWorkingDirectory)/**/target/*.war'
        ArtifactName: 'warFiles'
        publishLocation: 'Container'